version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=my-todo-list
    volumes:
      - my_todo_list_pg_data:/bitnami/postgresql

volumes:
  my_todo_list_pg_data: